services:
- type: web
  name: backend
  env: node
  region: oregon
  rootDir: backend
  buildCommand: npm install
  startCommand: npm start
  envVars:
  - key: SUPABASE_URL
    sync: false
  - key: SUPABASE_KEY
    sync: false